const dummys = [
  {
    review_Id: 35253,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 14,
    subCategory_Name: "크림 & 밤",
    barnd_Id: 605,
    barnd_Name: "슈베스",
    Product_Id: 82251783740,
    product_Title: "베이비 수딩젤",
    user_Id: 13167,
    user_NickName: "꼬실이네 축복맘",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_13167_1662445320356.jpeg?",
    ProductReview_content:
      "친구가 아기태열 잡는데 좋았다고 선물해주었어요 :) 수딩젤인만큼 여름에 쓰기 좋은 제품인 것 같아요",
    ProductReview_Content_bad:
      "그래도 약간 중간위험도 성분이 있다는게 아쉽고 , 수딩젤이라 수분감 유지는 안되서 수분공급은 크림으로 따로 해줘야해요 ~~",
    rating: 5,
    createdAt: "2022-09-06T15:22:02",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35252,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 14,
    subCategory_Name: "크림 & 밤",
    barnd_Id: 78,
    barnd_Name: "닥터바이오",
    Product_Id: 82251791654,
    product_Title: "에코 수딩젤",
    user_Id: 13167,
    user_NickName: "꼬실이네 축복맘",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_13167_1662444978927.jpeg?",
    ProductReview_content:
      "아기 태열에 좋다고해서 구매했어요 ~~ 닥터바이오 수딩젤 워낙 유명하고 대용량이라 가격대비 맘에들어요 ~",
    ProductReview_Content_bad:
      "아쉬운 점은 그래두 알러지 일으킬 수 있는 성분은 쪼금은 들어가있더라구요 ! 신생아때는 쪼금 걱정되서, 생후 3개월뒤부터 사용하려합니닷 ㅎㅎ",
    rating: 5,
    createdAt: "2022-09-06T15:16:19",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35251,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 12,
    subCategory_Name: "로션 & 에센스",
    barnd_Id: 211,
    barnd_Name: "일리윤",
    Product_Id: 82251787858,
    product_Title: "울트라 리페어 로션",
    user_Id: 13167,
    user_NickName: "꼬실이네 축복맘",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_13167_1662444641240.jpeg?",
    ProductReview_content:
      "가을 겨울철 바디로션으로 쓰고있는데, 촉촉하고, 성분좋아요 ! 참고로 저는 임산부입니당 ㅎㅎ ",
    ProductReview_Content_bad:
      "촉촉한만큼 약간 끈적거리는것도 있으니, 여름에 쓰기엔 좀 힘들어요 ㅎㅎ ",
    rating: 5,
    createdAt: "2022-09-06T15:10:42",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35250,
    category_Id: 7,
    category_Name: "임산부",
    subCategory_Id: 28,
    subCategory_Name: "임산부크림",
    barnd_Id: 211,
    barnd_Name: "일리윤",
    Product_Id: 82251779682,
    product_Title: "튼살크림",
    user_Id: 13167,
    user_NickName: "꼬실이네 축복맘",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_13167_1662444503931.jpeg?",
    ProductReview_content:
      "일단 임신 30주까지 튼살이 1도 안생겼어요 ! ㅎㅎ 대용량으로 구매하니 가격도 좋고 성분도 순해서 저는계속 일리윤쓰고있습니다 . 보습감이 좋아요 !",
    ProductReview_Content_bad:
      "여름에바르기에는 많이 촉촉해요 ㅋㅋㅋ 하지만 튼살안생기려면 열심히 발라야쥬~~",
    rating: 5,
    createdAt: "2022-09-06T15:08:24",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35249,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 12,
    subCategory_Name: "로션 & 에센스",
    barnd_Id: 674,
    barnd_Name: "제로솝",
    Product_Id: 82251780116,
    product_Title: "울트라 라이트 로션",
    user_Id: 13167,
    user_NickName: "꼬실이네 축복맘",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_13167_1662444297755.jpeg?",
    ProductReview_content:
      "일단 유해성분이 없어서 너어무좋아요. 신생아로션으로 준비했구요, 라이트하지만 촉촉해요^^",
    ProductReview_Content_bad: "딱히 아쉬운 점 없음 ! ",
    rating: 5,
    createdAt: "2022-09-06T15:04:58",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35248,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 12,
    subCategory_Name: "로션 & 에센스",
    barnd_Id: 56,
    barnd_Name: "그린핑거",
    Product_Id: 82251787182,
    product_Title: "포레스트 마일드 너츠 로션",
    user_Id: 13167,
    user_NickName: "꼬실이네 축복맘",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_13167_1662444070414.jpeg?",
    ProductReview_content:
      "제형이 되게 부드러운데, 보습감이 너무좋아서 온가족이 함께 사용하기 좋을듯해요^-^~~~~ 용량도 대용량이라 최고 !",
    ProductReview_Content_bad: "아기가 쓰기에는 향이 약간 강하다는 것! ",
    rating: 4,
    createdAt: "2022-09-06T15:01:11",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35247,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 14,
    subCategory_Name: "크림 & 밤",
    barnd_Id: 226,
    barnd_Name: "베베루나",
    Product_Id: 82251778603,
    product_Title: "마일드 수딩젤",
    user_Id: 8039,
    user_NickName: "래진",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_8039_1662442554557.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_8039_1662442554795.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_8039_1662442554894.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_8039_1662442554996.jpeg?",
    ProductReview_content:
      "[체험단 리뷰입니다] 여름내내 끈적임때문에 잠시 수딩젤은 멀리했었는데 베베루나마일드수딩젤 은 빠르게 흡수되고 산뜻함만 남아서 더운여름도 문제없어요 ◡̎ !!! 워터젤 타입이라 쿨링감이 있구요 건조하다 싶은 부위에 바르면 즉각적으로 수분이 공급되어 바로바로 촉촉함을 느낄수 있어요~ 정제수 대신 엘더꽃 추출물을 사용해서 피부진정효과가 뛰어나고, 자극지수가 무려 0.00인 비자극 화장품이라 신생아부터 민감피부 어른까지 사용가능해요 !!! 땀띠올라오고 햇빛알러지에도 빠르게 진정되는 제품입니다^^",
    ProductReview_Content_bad:
      "아쉬운점 없어요 아가랑 엄마랑 함께쓰니 빨리사용하게 되네요^^ 대용량도 출시되었으면 좋겠어요~",
    rating: 5,
    createdAt: "2022-09-06T14:35:07",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35246,
    category_Id: 6,
    category_Name: "세정제",
    subCategory_Id: 23,
    subCategory_Name: "치약",
    barnd_Id: 1242,
    barnd_Name: "생활도감",
    Product_Id: 82251782873,
    product_Title: "생활도감 치약 쿨민트",
    user_Id: 15094,
    user_NickName: "다림단감",
    ProductReview_Url: null,
    ProductReview_content:
      "제형은 묽어요. 그러나 사용감과 마무리감이 무척 상쾌합니다🤍 재구매해서 늘 사용하고 있어요. 초반엔 조금 맵게 느껴질 수가 있는데, 양치하고 나면 꽤나 오랫동안 입안이 상쾌합니다. 임신하고 입덧 중엔 특히 시중에 저렴하게 판매되는 치약과 비교했을 때 가글하고 뱉어낼때 구역감(?)같은게 덜 느껴지기도 했던 치약이에요.",
    ProductReview_Content_bad:
      "제형이 묽고 약간 흐르는 편이라 소모량이 은근히 빠르다는 점. 그리고 뚜껑이 작고 돌려 잠그는 형태라 다소 귀찮기도 해요.",
    rating: 5,
    createdAt: "2022-09-06T09:50:43",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35245,
    category_Id: 1,
    category_Name: "간식",
    subCategory_Id: 4,
    subCategory_Name: "음료",
    barnd_Id: 2035,
    barnd_Name: "맘스초이스",
    Product_Id: 82251788034,
    product_Title: "배도라지주스",
    user_Id: 175,
    user_NickName: "건우맘486",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_175_1662384180550.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_175_1662384180707.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_175_1662384180848.jpeg?",
    ProductReview_content:
      "#체험단리뷰 어렸을 때 제가 천식을 앓아서 호흡기가 약한 편인데, 아이들도 엄마의 영향인지 감기도 잘 걸리고 호흡기가 취약해서 집에 항상 도라지배즙을 구비해 두거든요. 아직 막내가 어려서 배주스를 주곤 했는데, 배 100프로보다는 배도라지가 더 나을 것 같아서 어떤 제품을 막내의 첫 배도라지 주스로 알맞을 지 고민하던 차에 맘스초이스 배도라지 착즙주스를 체험해보게 되어 참 기뻤어요ㅎㅎ 직접 체험하면서 너무 마음에 들었던 부분, 1. NFC착즙 100프로, 2. 무보존료, 무착향료, 무색소인 것~ 3. 4살 딸이 흘리지 않고 스스로 먹을 수 있는 편리한 입구부분 이예요. 사실, 착즙 주스(과채주스)라 해도 주스 색이 배 속살과 같은 주스는 처음 봤어요. 중탕보다는 착즙이 좋다고 해서 구매해봤는데, 중탕식보다 색이 좀 밝은 정도였지, 이 정도로 밝은 색은 처음 봤거든요. 그 정도로 100프로 착즙인 셈이니 먹이면서도 안심되고 좋더라구요 :) 한 팩에 양도 너무 적지 않은 120ml에, 맛도 너무 달지 않아서 더 만족!!! ",
    ProductReview_Content_bad:
      "아쉬운 점은 딱히 모르겠고... 아무래도 착즙음료니 금액은 저렴한 편은 아니예요~ 그래도 맛이며 식감도 좋아서 합리적인 것 같기도 하네요~ ",
    rating: 5,
    createdAt: "2022-09-05T22:23:02",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35244,
    category_Id: 1,
    category_Name: "간식",
    subCategory_Id: 4,
    subCategory_Name: "음료",
    barnd_Id: 2035,
    barnd_Name: "맘스초이스",
    Product_Id: 82251788034,
    product_Title: "배도라지주스",
    user_Id: 5231,
    user_NickName: "원주은우맘",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_5231_1662381562351.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_5231_1662381564059.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_5231_1662381565086.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_5231_1662381566971.jpeg?",
    ProductReview_content:
      "#협찬 #제품제공 💗맘스초이스 배도라지주스💗 요즘같이 갑자기 추워지는 날씨에 온가족이 함께 먹기 너무 좋은 맘스초이스 배도라지주스🙂 📌100% 국내산 원물만 사용 📌100% NFC착즙 (물 한방울없이 원물로만 착즙 ) 📌무설탕, 무색소, 무향료, 무방부제, 무정제수 ! 📌휴대와 마시기 편리한 스파우트 파우치 ! 은은한 도라지향과 달달한 배맛으로 맛도 조화롭고 건강에도 최고예요👍 시중에서 유통되는 과채음료나 액상차, 혼합차가 아니라 배와 도라지를 통째로 혼합해서 착즙한 과채주스여서 그런지 맛이 정말 진하고 좋았어요🥰 달콤해서 마시기도 좋았는데 설탕이나 첨가물의 단맛이 아니라 원물 본연의 단맛이 느껴져서 진하지만 가볍게 마실 수 있는것 같아요 ! 임산부나 영유아도 먹을 수 있고 남녀노소 누구나 먹을 수 있는 안전한 과채주스 맘스초이스 배도라지주스❤️ 더울땐 냉장고에 넣어뒀다가 시원하게 먹어두 맛있고 요즘같은 날씨엔 따뜻하게 데워서 가볍게 한잔씩 마시고 잠자리에 드는것도 추천합니다😃 #베럽 #베럽체험단 #맘스초이스 #맘스초이스배도라지주스 #NFC착즙주스 #착즙주스 #과채주스 #건강주스 #국내산도라지 #목건강 #환절기건강 #감기예방 #배도라지즙 #아이들간식 #가족선물 #아이선물 #친구선물 ",
    ProductReview_Content_bad: "아쉬운점 없이 너무 좋아요! 적극 추천합니다❤️",
    rating: 5,
    createdAt: "2022-09-05T21:39:28",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35243,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 11,
    subCategory_Name: "바디워시",
    barnd_Id: 101,
    barnd_Name: "록시땅",
    Product_Id: 82251791942,
    product_Title: "시어 울트라 리치 핸드 앤 바디 워시",
    user_Id: 14218,
    user_NickName: "하잉님",
    ProductReview_Url: null,
    ProductReview_content:
      "아주 묽은 제형이라 자주 손 씻기에 가볍고 아주 과하지 않은 부드러운 록시땅 시어버터향이라 좋아요!",
    ProductReview_Content_bad:
      "아주 묽은 제형이라 펌핑을 꾹 하면 쭉~ 튀면서 발사되는 느낌이라 쓰기가 조금 불편한적도 있었어요 ㅠㅠ",
    rating: 4,
    createdAt: "2022-09-05T21:07:44",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35242,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 14,
    subCategory_Name: "크림 & 밤",
    barnd_Id: 226,
    barnd_Name: "베베루나",
    Product_Id: 82251778603,
    product_Title: "마일드 수딩젤",
    user_Id: 14365,
    user_NickName: "슬기로운호떡",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/name8AC56ABD-3E9C-4E36-B5E7-D84AA8D80628.jpg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/name899BC07E-BAD1-46F3-8E66-547B1135DAB2.jpg?",
    ProductReview_content:
      "(체험단 리뷰) 수딩젤 유목민으로 여기저기 제품 써보는 중에 감사하게도 체험단으로 제품 제공 받아서 써보게 되엇어요 항상 수딩젤 바르고 나면 더 건조한 느낌이 많더라구요 일단 베베루나 수딩젤은 바르고 나서도 촉촉해서 좋앗어요 손 씻고 나서도 로션대신 몇번 발랏는데 끈적함 없이 촉촉한감이 오래 가더라구요 향도 은은하게 나서 호불호 없을거 같고 바르고 나서도 기분이 좋네요 ㅎㅎ 아기가 살짝 건조한 피부이고 기저귀 부분이 습해서 항상 신경 쓰는데 이 제품 받고 나서 듬뿍 바르고 잇는데 바르자마자 흡수력도 좋고 촉촉하네요 성분도 착해서 믿을만 하고 안심하고 쓸수 잇을거 같아요 👍🏻",
    ProductReview_Content_bad:
      "아쉬운점은 아직 없어요 만족하면서 쓰고 잇습니다 ~!",
    rating: 5,
    createdAt: "2022-09-05T17:49:52",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35241,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 11,
    subCategory_Name: "바디워시",
    barnd_Id: 280,
    barnd_Name: "해피바스",
    Product_Id: 82251782975,
    product_Title: "로즈 에센스 브라이트닝 바디워시",
    user_Id: 14632,
    user_NickName: "또여니맘",
    ProductReview_Url: null,
    ProductReview_content:
      "향이 좋아요~피부건조한 남.편도 맘에든데요~ 계속 이제품만 쓸려고하네요",
    ProductReview_Content_bad: "단점없어요~",
    rating: 5,
    createdAt: "2022-09-05T16:17:12",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35240,
    category_Id: 6,
    category_Name: "세정제",
    subCategory_Id: 22,
    subCategory_Name: "젖병 & 주방세제",
    barnd_Id: 356,
    barnd_Name: "그린맘",
    Product_Id: 82251779142,
    product_Title: "거품형 젖병세정제",
    user_Id: 14632,
    user_NickName: "또여니맘",
    ProductReview_Url: null,
    ProductReview_content:
      "타제품액상형사용하다 처음거품형써보니 편해요!거품도 풍성하고 뽀득뽀득해요!",
    ProductReview_Content_bad: "만족하며 사용중입니다!",
    rating: 5,
    createdAt: "2022-09-05T15:15:37",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35239,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 11,
    subCategory_Name: "바디워시",
    barnd_Id: 173,
    barnd_Name: "케이맘",
    Product_Id: 82251780934,
    product_Title: "처음 스킨케어 2in1 헤어 앤 바디워시",
    user_Id: 14632,
    user_NickName: "또여니맘",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_14632_1662358355873.jpeg?",
    ProductReview_content: "사용하기편리해요 거품이 보들보들해요",
    ProductReview_Content_bad: "리필형이없어서 아쉬워요",
    rating: 5,
    createdAt: "2022-09-05T15:12:36",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35238,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 12,
    subCategory_Name: "로션 & 에센스",
    barnd_Id: 173,
    barnd_Name: "케이맘",
    Product_Id: 82251780929,
    product_Title: "처음 로션",
    user_Id: 14632,
    user_NickName: "또여니맘",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_14632_1662358145169.jpeg?",
    ProductReview_content:
      "신생아부터 사용한 로션이예요!!7개월째 사용중입니다!!보습력도 좋아요!!",
    ProductReview_Content_bad: "없어요~",
    rating: 5,
    createdAt: "2022-09-05T15:09:05",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35237,
    category_Id: 6,
    category_Name: "세정제",
    subCategory_Id: 22,
    subCategory_Name: "젖병 & 주방세제",
    barnd_Id: 1421,
    barnd_Name: "베르블랑",
    Product_Id: 82251789181,
    product_Title: "주방세제 1종 퓨리그린향",
    user_Id: 14975,
    user_NickName: "최또이",
    ProductReview_Url: null,
    ProductReview_content: "향도 좋고 세정력도 좋아요",
    ProductReview_Content_bad: "뽀득한 느낌을 좋아하는데 미끌한 느낌이 남아요",
    rating: 5,
    createdAt: "2022-09-05T08:34:10",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35236,
    category_Id: 6,
    category_Name: "세정제",
    subCategory_Id: 20,
    subCategory_Name: "세탁세제",
    barnd_Id: 1421,
    barnd_Name: "베르블랑",
    Product_Id: 82251783994,
    product_Title: "세탁비누(머스크향)",
    user_Id: 14975,
    user_NickName: "최또이",
    ProductReview_Url: null,
    ProductReview_content:
      "아가 한창 뒤집기 할때 많이 게워내고 해서 애벌 빨래용으로 사용했어요 응가도 잘 지워져요 향도 세정력도 좋아요",
    ProductReview_Content_bad:
      "애벌세탁 하다보면 빨래비누 특성의 빨래물이 좀 오래 나와요",
    rating: 5,
    createdAt: "2022-09-05T08:32:36",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35235,
    category_Id: 6,
    category_Name: "세정제",
    subCategory_Id: 25,
    subCategory_Name: "섬유유연제",
    barnd_Id: 1421,
    barnd_Name: "베르블랑",
    Product_Id: 82251784907,
    product_Title: "섬유유연제 베이비 머스크향",
    user_Id: 14975,
    user_NickName: "최또이",
    ProductReview_Url: null,
    ProductReview_content:
      "향 진짜 너무 좋아요 건조대 널면 향이 솔솔 기분까지 좋아집니다",
    ProductReview_Content_bad:
      "금액이 조금만 저렴하면 좋을텐데 할인특가 노려야해요",
    rating: 5,
    createdAt: "2022-09-05T08:30:42",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35234,
    category_Id: 6,
    category_Name: "세정제",
    subCategory_Id: 20,
    subCategory_Name: "세탁세제",
    barnd_Id: 1421,
    barnd_Name: "베르블랑",
    Product_Id: 82251783967,
    product_Title: "중성 아기세제 무향",
    user_Id: 14975,
    user_NickName: "최또이",
    ProductReview_Url: null,
    ProductReview_content:
      "아기 세제라 무향을 선호하는 편이예요 세정력도 나쁘지 않고 잘 쓰고 있습니다",
    ProductReview_Content_bad: "금액이 저렴하진 않아요",
    rating: 5,
    createdAt: "2022-09-05T08:29:36",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35233,
    category_Id: 4,
    category_Name: "물티슈",
    subCategory_Id: 10,
    subCategory_Name: "물티슈",
    barnd_Id: 420,
    barnd_Name: "앙블랑",
    Product_Id: 82251779386,
    product_Title: "아기물티슈 인디핑크",
    user_Id: 14975,
    user_NickName: "최또이",
    ProductReview_Url: null,
    ProductReview_content:
      "얇은 엠보예요 금액도 괜찮은편이라 여기저기 막 쓰기 좋아요 특히 아가 장난감 소독할때 잘 쓰고 있어요",
    ProductReview_Content_bad:
      "블랙 정도 엠보를 좋아하는편이라 개인적으로 얇아서 아기 응가 처리는 조금 힘들어요🥲",
    rating: 5,
    createdAt: "2022-09-05T08:27:13",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35232,
    category_Id: 4,
    category_Name: "물티슈",
    subCategory_Id: 10,
    subCategory_Name: "물티슈",
    barnd_Id: 420,
    barnd_Name: "앙블랑",
    Product_Id: 82251779390,
    product_Title: "아기물티슈 블랙",
    user_Id: 14975,
    user_NickName: "최또이",
    ProductReview_Url: null,
    ProductReview_content:
      "한장씩 잘 뽑히고 아가 엉덩이 닦아줄때 부드럽고 좋아요",
    ProductReview_Content_bad: "매수에 비해 저렴한 편은 아니예요",
    rating: 5,
    createdAt: "2022-09-05T08:23:18",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35231,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 14,
    subCategory_Name: "크림 & 밤",
    barnd_Id: 226,
    barnd_Name: "베베루나",
    Product_Id: 82251778603,
    product_Title: "마일드 수딩젤",
    user_Id: 2470,
    user_NickName: "써니럽미",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_2470_1662296245913.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_2470_1662296245945.jpeg?",
    ProductReview_content:
      "진짜 좋아요~ 아이가 수족구 일주일 앓고 종일 긁어대고ㅠ 맘아팠거든요ㅜ 피부가 예전에 비해서 너무 건조해져서 쩍쩍 갈라지고요ㅠ 수분 보습이 진짜 필요할때 베베루나수딩젤을 만나게되서 써봤는데 바를때 촉촉하고요♡ 잘스며들어서 피부가 보송해요~ 발림이 가볍고 좋아서 여러번 덧바르기도 좋구요~ 샤워후 뿐만 아니라 평소 생각날때면 계속 발라준답니다",
    ProductReview_Content_bad:
      "트러블도 없고 향도 좋고 아쉬운게 딱히 없어요~^^ 만족스러워요",
    rating: 5,
    createdAt: "2022-09-04T21:57:26",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35230,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 14,
    subCategory_Name: "크림 & 밤",
    barnd_Id: 226,
    barnd_Name: "베베루나",
    Product_Id: 82251778603,
    product_Title: "마일드 수딩젤",
    user_Id: 2043,
    user_NickName: "army188",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_2043_1662295943236.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_2043_1662295943393.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_2043_1662295943566.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_2043_1662295943772.jpeg?",
    ProductReview_content:
      "진정에는 수딩젤이 최고라서 꼭 사용합니다 아기 로션 바르기전에 잘 챙겨바르면 피부가 촉촉한게 오래가서 좋더라구요 어떤 제품은 바르고나면 촉촉하지만 나중엔 더 건조해지는데 베베루나는 촉촉함이 오래가고 로션이라 크림으로 마무리해주면 딱 적당하더라구요 또 엘더플라워추출물 때문인가요? 향이 들꽃향처럼 풋풋하면서도 은은해서 마음에 들더라구요 칫솔질하고 입주변이 건조한지 뾰루지처럼 붉게 달아올랐는데 바로 발라줬더니 금방 진정되었어요 심하게 건조하거나 자극받은 피부에 안심하고 쓸 수딩젤을 찾은것같아요 저도 설겆이에 집안일하다가 건조한 손에 발랐는데 크림으로 마무리 안했는데도 촉촉했어요 이부분이 정말 최고이지 않나 싶어요 달팽이 추출물 판테놀 등등 다른 좋은 성분도 들어가있어서 그런 것 같아요 베럽체험단으로 선정되어 체험 후 남기는 후기입니다",
    ProductReview_Content_bad:
      "전혀 아쉬운 점이 없어요 잘 알려지지 않은게 아쉽네요~ ",
    rating: 5,
    createdAt: "2022-09-04T21:52:25",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35229,
    category_Id: 1,
    category_Name: "간식",
    subCategory_Id: 4,
    subCategory_Name: "음료",
    barnd_Id: 2035,
    barnd_Name: "맘스초이스",
    Product_Id: 82251788034,
    product_Title: "배도라지주스",
    user_Id: 10894,
    user_NickName: "오리대장",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_10894_1662267160394.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_10894_1662267161291.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_10894_1662267162427.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_10894_1662267163488.jpeg?",
    ProductReview_content:
      "맘스초이스 배도라지 주스 2박스만 온줄 알았더니 사은품도 같이 왔어요ㅎㅎ 니가 왜 거기서 나와♪ 100% 국내산 통과일 사과주스 2봉을 서비스로 챙겨주셨어요ㅎㅎ 원재료명에도 정말 국내산 사과 100%만 써있으니 믿고 먹을 수 있고 포장지 그림도 너무 귀여워요! 맘스초이스 배도라지 주스는 한박스에 7봉이 들어있어요 맘스초이스 배도라지 주스 역시 마찬가지로 원재료가 국내산 배 97%, 국내산 도라지3%로 구성되어 있어 합성보존료나 색소, 첨가물이 들어있지 않아 아기가 안심하고 먹을 수가 있어요~ 유통기한도 23년까지로 넉넉합니다!! 정말 믿고 마실 수 있는 국내산 재료들로만 착즙해서 만든 주스라서 우리 아이 면역력을 위해 마셔보라고 컵에 담아주었는데요 아이가 입맛이 까다로운데도 숨도 안쉬고 꿀걱꿀걱 잘 먹더라구요ㅎㅎ 아이 입맛이 딱 맞았나봐요~ 이제 환절기가 찾아오고 독감의 계절도 찾아왔는데 배도라지 주스 챙겨먹고 면역력도 챙기자구요! (주관적인 체험단 리뷰입니다.)",
    ProductReview_Content_bad: "없음",
    rating: 5,
    createdAt: "2022-09-04T13:51:12",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35228,
    category_Id: 1,
    category_Name: "간식",
    subCategory_Id: 1,
    subCategory_Name: "과자 & 칩",
    barnd_Id: 1496,
    barnd_Name: "퓨어잇",
    Product_Id: 82251784410,
    product_Title: "퓨어잇떡뻥 시금치쌀과자",
    user_Id: 4546,
    user_NickName: "사과맘",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_4546_1662250184134.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_4546_1662250184307.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_4546_1662250184486.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_4546_1662250184660.jpeg?",
    ProductReview_content:
      "길쭉하고 잡기 편해서인지 아기가 잘 잡고 먹어요! 쌀99% 라서 엄청 고소하고 단백해요 ",
    ProductReview_Content_bad:
      "시금치 함유 1%라 그런지 시금치 맛이 하나도 안나요",
    rating: 4,
    createdAt: "2022-09-04T09:09:46",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35227,
    category_Id: 1,
    category_Name: "간식",
    subCategory_Id: 4,
    subCategory_Name: "음료",
    barnd_Id: 2462,
    barnd_Name: "돌",
    Product_Id: 82251791891,
    product_Title: "하이! 애플 주스",
    user_Id: 4480,
    user_NickName: "뚀으미",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_4480_1662216279243.jpeg?",
    ProductReview_content:
      "한번씩 외출했을때 먹이고있어요 ㅎㅎ 팩에그려진 사과캐릭터가 귀여워요! 크기도 작아서 아이가 잡고먹기 편하고 외출시에도 가방에 크게 부피차지를 하지않아 좋아요 😀 ",
    ProductReview_Content_bad: "인공적인향이 살짝나요 ",
    rating: 5,
    createdAt: "2022-09-03T23:44:39",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35226,
    category_Id: 1,
    category_Name: "간식",
    subCategory_Id: 4,
    subCategory_Name: "음료",
    barnd_Id: 2035,
    barnd_Name: "맘스초이스",
    Product_Id: 82251788029,
    product_Title: "100% 국내산 통과일 어린이 사과주스",
    user_Id: 4480,
    user_NickName: "뚀으미",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_4480_1662215800790.jpeg?",
    ProductReview_content:
      "아이가 너무 잘먹어요 ㅎㅎ 한번먹기 양도 적당하고 사과주스 좋아하는데 성분이 좋아서 이걸로 계속 사먹여도 괜찮겠어요 ㅎㅎ 무엇보다 아이가 잘먹으니 좋네요 ㅎㅎ",
    ProductReview_Content_bad: null,
    rating: 5,
    createdAt: "2022-09-03T23:36:41",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35225,
    category_Id: 1,
    category_Name: "간식",
    subCategory_Id: 4,
    subCategory_Name: "음료",
    barnd_Id: 2035,
    barnd_Name: "맘스초이스",
    Product_Id: 82251788034,
    product_Title: "배도라지주스",
    user_Id: 4480,
    user_NickName: "뚀으미",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_4480_1662215532119.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_4480_1662215532862.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_4480_1662215533335.jpeg?",
    ProductReview_content:
      "<🌷체험단리뷰입니다🌷> 이제 조금씩 날씨가 추워지고있어 아이 기관지관리는 지금부터 해줘야해요 ㅎㅎ 맘스초이스 배도라지 주스는 스파우트 형식 으로 아이가 혼자 먹기에도 편하고 외출시에도 따로 컵이나 빨대컵 을 챙기거나 할 필요가 없어 너무편하네요 ㅎㅎ 용량도 한번에 먹기부담스럽지않은 적당한양이예요 ! 내용물 사진으로 보여드리려고 유리컵에 부어서 사진찍는데 딸램 빨리먹고싶다고 내놔라고 난리난리 ... 사진찍고 주자마자 벌컥벌컥 마셔요 ㅎㅎ 정말 맛있나봐요 잘먹어요 ! 배맛이많이나고 도라지맛이 은은하게 나요 아이가 먹는거라 밍밍할줄 알았는데 그렇게 많이 연하지도 않고 순하고 괜찮네요 ㅎㅎ 별다른 식품첨가물이 없어 안심하고먹일수있어요. 배랑 도라지만 들어갓는데도 맛있어요 ㅎㅎ ",
    ProductReview_Content_bad: "아쉬운점 없어요 만족합니다 ㅎㅎ",
    rating: 5,
    createdAt: "2022-09-03T23:27:00",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35224,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 14,
    subCategory_Name: "크림 & 밤",
    barnd_Id: 226,
    barnd_Name: "베베루나",
    Product_Id: 82251778603,
    product_Title: "마일드 수딩젤",
    user_Id: 2458,
    user_NickName: "보보88",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_2458_1662209286404.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_2458_1662209286442.jpeg?",
    ProductReview_content:
      "진짜 향부터가 너무 좋아요! 특히 신랑이 좋아합니다ㅎ 평소 향수도 뿌리는 사람이라 향에 예민한데 베베루나수딩젤 향 좋다고 자꾸 아이한테 킁킁하면서 냄새맡아요ㅋㅋ 촉촉해서 발림성 좋구요~ 가볍고 산뜻해서 흡수잘됩니다ㅎ 아가 피부가 맨들맨들해요ㅎㅎ 건조한피부인데 당김없이 좋아요",
    ProductReview_Content_bad:
      "가격대가 조금 비싸다는게 아쉽지만 좋은성분이기에 그러려니 이해되긴해요^^",
    rating: 5,
    createdAt: "2022-09-03T21:48:08",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35223,
    category_Id: 6,
    category_Name: "세정제",
    subCategory_Id: 25,
    subCategory_Name: "섬유유연제",
    barnd_Id: 1627,
    barnd_Name: "웨일리",
    Product_Id: 82251785391,
    product_Title: "고농축 섬유유연제",
    user_Id: 3210,
    user_NickName: "샤블",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_3210_1662208905051.jpeg?",
    ProductReview_content:
      "온가족 세제여서 아기빨래 같이할때 안심하고 사용할수있더라구요 !! 라벤더 향으로 은은하고 꿉꿉한 냄세없고 옷감도 부드러워요 ! 너무좋네요~~",
    ProductReview_Content_bad: "아쉬운점은 따로 없었어요 ~~",
    rating: 5,
    createdAt: "2022-09-03T21:41:46",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35222,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 14,
    subCategory_Name: "크림 & 밤",
    barnd_Id: 226,
    barnd_Name: "베베루나",
    Product_Id: 82251778603,
    product_Title: "마일드 수딩젤",
    user_Id: 9502,
    user_NickName: "호야luv",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_9502_1662208570428.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_9502_1662208570674.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_9502_1662208570912.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_9502_1662208571142.jpeg?",
    ProductReview_content:
      "<체험리뷰> 제가 임신중이라 손등이랑 발등에 가려움이 생겨서 많이 민감한 피부가 되어서 밤마다 잠을 못자고 있었는데... 마침 수딩젤이진정효과에 좋다고해서 냉장고에 넣어놓고 시원하게 사용해보았어요. 직접사용해보니 촉촉하고 피부가 금방진정되서 오! 이거다싶었어요 👍 그리고 피부자극테스트완료된 제품이라 건조함이 가득한 가을날 🍂 태어날 우리아기에게도 믿고 사용할수있을거같아요 ^^ 아기를 포함해 우리가족들 건조한피부도 믿고 맡길수 있을거같아기대되요 👨‍👩‍👧 그전에 제가 먼저 1통 다써야겠습니다 😄",
    ProductReview_Content_bad:
      "아쉬운점은 크게없는거같아요~ 전 무척 만족하며 사용중입니다 😊",
    rating: 5,
    createdAt: "2022-09-03T21:36:12",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35221,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 14,
    subCategory_Name: "크림 & 밤",
    barnd_Id: 226,
    barnd_Name: "베베루나",
    Product_Id: 82251778603,
    product_Title: "마일드 수딩젤",
    user_Id: 9321,
    user_NickName: "운호엄마",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/name225D6022-807A-48F9-81BB-CE0028E570EC.jpg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/name2D2FD093-69B6-45D2-8873-F9F0202C7546.jpg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/name248EDEA4-C76D-4226-ABC2-39C4F4996136.jpg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/nameBD645A09-4462-4232-B02C-47EDE7ED7985.jpg?",
    ProductReview_content:
      "촉촉한 마무리감으로 보습력 너무 좋아요!! 수딩젤이라서 더울때 여름에 사용하기 너무 딱이구여! 용량이 160g 으로 정말 넉넉하서 오래 쓸꺼같아요! 순해서 따로 뭐 얼굴이 나는것더 없고 건조한 피부에는 수분감 채워주기에 가장 안성맞춤인 제품입니다! 재구매 생각 있는 제품입니다!! 피부자극 테스트도 완료됨 안전한 제품이라서 주위에 추천도 마노이 해야겠습니다!",
    ProductReview_Content_bad: "아쉬운 점을 찾지 못하였네요ㅠㅠ!!!",
    rating: 5,
    createdAt: "2022-09-03T17:44:46",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35220,
    category_Id: 1,
    category_Name: "간식",
    subCategory_Id: 4,
    subCategory_Name: "음료",
    barnd_Id: 1584,
    barnd_Name: "엘빈즈",
    Product_Id: 82251789505,
    product_Title: "통째로 으깬 옥수수 퓨레",
    user_Id: 4546,
    user_NickName: "사과맘",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_4546_1662175674122.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_4546_1662175674329.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_4546_1662175674506.jpeg?",
    ProductReview_content:
      "맛은 단 맛이 아주아주아주 조금 나는 느낌의 옥수수 맛이예요 맛 없지는 않지만 약간 가짜 옥수수 맛? 그래도 9개월 아기가 잘 먹어요~ 제형은 엄청 단단한 느낌이 커요 주먹밥처럼 동그랗게 빚어서 간식으로 주기 좋아요",
    ProductReview_Content_bad:
      "꼭 전자레인지 사용해야할 것 같아요 안그러면 9개월 아기에게 주기 힘들어요",
    rating: 4,
    createdAt: "2022-09-03T12:27:55",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35219,
    category_Id: 1,
    category_Name: "간식",
    subCategory_Id: 4,
    subCategory_Name: "음료",
    barnd_Id: 2035,
    barnd_Name: "맘스초이스",
    Product_Id: 82251788034,
    product_Title: "배도라지주스",
    user_Id: 3601,
    user_NickName: "jisue22 ",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_3601_1662171558836.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_3601_1662171558909.jpeg?",
    ProductReview_content:
      "[체험단리뷰입니다] 12개월 아기 처음으로 배도라지 음료 먹인 게 맘스 초이스 배도라지 음료에요 지금까지는 이유식이며 간식 다 만들어서 먹였는데 배도라지는 손이 너무 많이 가서 도저히 만들 엄두가 안나더라고요 그러다 맘스 초이스 제품을 알게 됐는데 다른 첨가물없이 100프로 배와 도라지만 들어가서 믿고 먹일 수 있겠더라구요 사이즈도 아기가 들고 먹기 딱 좋아서 아기 손에 쥐어주고 먹여요 맛없는 건 잘 안 먹는 우리 애기가 처음부터 너무 잘 먹었고 자기가 먼저 찾아요 진짜 만족 백프로 합니다 ",
    ProductReview_Content_bad: "아쉬운 점 1도 없어요 너무좋아요",
    rating: 5,
    createdAt: "2022-09-03T11:19:22",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35218,
    category_Id: 3,
    category_Name: "기저귀",
    subCategory_Id: 9,
    subCategory_Name: "해외기저귀",
    barnd_Id: 1663,
    barnd_Name: "팸퍼스",
    Product_Id: 82251787565,
    product_Title: "통잠팬티 5단계",
    user_Id: 2884,
    user_NickName: "혀니맘0807",
    ProductReview_Url: null,
    ProductReview_content:
      "타 기저귀 사용하다가 자꾸 새서 사용해봤어요! 흡수력도 좋고 밤새 뒤척여도 샘 없어요!! 기저귀 발진도 없어요 짱!",
    ProductReview_Content_bad: null,
    rating: 4,
    createdAt: "2022-09-03T07:12:01",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35217,
    category_Id: 3,
    category_Name: "기저귀",
    subCategory_Id: 9,
    subCategory_Name: "해외기저귀",
    barnd_Id: 1663,
    barnd_Name: "팸퍼스",
    Product_Id: 82251786743,
    product_Title: "에어차차 썸머팬티 5단계",
    user_Id: 2884,
    user_NickName: "혀니맘0807",
    ProductReview_Url: null,
    ProductReview_content:
      "타 기저귀 사용하다가 자꾸 새서 사용해봤어요! 흡수력도 좋고 밤새 뒤척여도 샘 없어요!! 기저귀 발진도 없어요 짱!",
    ProductReview_Content_bad: "가격이 조금만 저렴하면 넘넘 좋을꺼같은....🫶",
    rating: 5,
    createdAt: "2022-09-03T07:10:50",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35216,
    category_Id: 3,
    category_Name: "기저귀",
    subCategory_Id: 9,
    subCategory_Name: "해외기저귀",
    barnd_Id: 1663,
    barnd_Name: "팸퍼스",
    Product_Id: 82251786605,
    product_Title: "아르모니 밴드형 3단계",
    user_Id: 2884,
    user_NickName: "혀니맘0807",
    ProductReview_Url: null,
    ProductReview_content:
      "흡수력도 좋고 새지않아서 일단 만족하며 사용중이예요!! 기저귀 발진도 없이 잘 사용하고 있습니다~~!",
    ProductReview_Content_bad: null,
    rating: 5,
    createdAt: "2022-09-03T07:08:47",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35215,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 12,
    subCategory_Name: "로션 & 에센스",
    barnd_Id: 655,
    barnd_Name: "스카이밀크",
    Product_Id: 82251790592,
    product_Title: "로션",
    user_Id: 172,
    user_NickName: "율이맘",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_172_1662310255969.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_172_1662310257011.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_172_1662310257616.jpeg?",
    ProductReview_content:
      "<체험단으로서 제품을 제공받아 작성된 후기입니다> 스카이밀크는 제품을 만들때 직영 농장에서 직접 당나귀밀크를 생산해 신선한 당나귀밀크와 식물유래성분으로 만들어진 제품이라고 하더라구요. 그래서 아이에게 사용할때 더 믿고 사용할수 있을것 같다는 생각이 들었어요. 로션 바를때 아이든 저든 바르고나서 흡수안되고 겉돌고 찝찝한건 딱 질색인데 끈적임 없이 피부에 잘 발려서 너무 좋아요.",
    ProductReview_Content_bad:
      "튜브형보다는 펌핑형이었으면 하고 용량이 좀 많으면 좋겠어요.",
    rating: 4,
    createdAt: "2022-09-02T23:52:38",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35214,
    category_Id: 1,
    category_Name: "간식",
    subCategory_Id: 4,
    subCategory_Name: "음료",
    barnd_Id: 2035,
    barnd_Name: "맘스초이스",
    Product_Id: 82251788034,
    product_Title: "배도라지주스",
    user_Id: 3579,
    user_NickName: "짱구짱아엄마입니다 ",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_3579_1662128991175.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_3579_1662128991792.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_3579_1662128992376.jpeg?",
    ProductReview_content:
      "(체험단으로 제품을 제공받아 직접체험후에 작성한 후기입니다 ) ㆍ 배도라지 주스는~이번 체험단을 통해서 처음 먹여봤어요. 어머낫..안좋아하면 어떡하지? 하는 걱정을 했는데 너무너무 잘먹더라구요. 빨대컵에 담아서 줬는데...정말 3번 숨쉴때 빼고는 원샷~ 했습니다.ㅋㅋㅋ 너무 잘 먹어주니 뿌듯하고 좋더라구용. 첨가물도 안들아간 주스라서 맘에들고요~ 다른맛도 구매해봐야겠어요. 너무 칭찬합니다.👍",
    ProductReview_Content_bad: "아쉬운점은.. 하나도 없네용~~~^^",
    rating: 5,
    createdAt: "2022-09-02T23:28:12",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35213,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 12,
    subCategory_Name: "로션 & 에센스",
    barnd_Id: 655,
    barnd_Name: "스카이밀크",
    Product_Id: 82251790592,
    product_Title: "로션",
    user_Id: 6738,
    user_NickName: "sealine83",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_6738_1662123608751.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_6738_1662123608818.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_6738_1662123608873.jpeg?",
    ProductReview_content:
      "로션이라 제형이 묽지도 무겁지도 않고 적당한로션제형이였어요 바르기 좋았고 일단 향이 은은해서 아이들에게 얘기하기도 전에 아이들이 너무 좋은향이라고^ ^ 당연히 트러블은 없었구요 끈적임과 미끄덩거림이 없고 촉촉함이 너무나 좋았던 스카이밀크 ",
    ProductReview_Content_bad:
      "튜브형이라 펌핑형이면 좀 더 좋았을거같고 가성비가 조금 아쉬웠어요 ",
    rating: 5,
    createdAt: "2022-09-02T22:00:09",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35212,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 12,
    subCategory_Name: "로션 & 에센스",
    barnd_Id: 655,
    barnd_Name: "스카이밀크",
    Product_Id: 82251790592,
    product_Title: "로션",
    user_Id: 4622,
    user_NickName: "알록맘",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_4622_1662119237947.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_4622_1662119239491.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_4622_1662119240200.jpeg?",
    ProductReview_content:
      "<체험단 리뷰 작성> 우와 일단 결론적으로 말하면 저랑 남편이랑 저희 애기 이걸로 정착하게 될것 같아요!!!! 구매의사 완전 있어요!!! 남편은 향이 좋다하더라도 너무 진한것도 싫어하고 향이 안좋은것도 싫어하는데 저랑 남편 요고 바르자마자 향부터 반했어요 ❤️ 그치만 향만 좋다고 구매 하진 않잖아요? 발림력이나 촉촉함도 완전 대박~ 부드럽게 발리고 촉촉한것도 오일 한방울?섞어서 바른거처럼 보습도 최고 👍 그렇다고 흡수안되고 끈적이거나 미끌하지도 않아요!! 애기거 따로 쓰지않고 온 가족 다같이 쓰고싶은 바디로션은 처음?인것 같아요 😍강추",
    ProductReview_Content_bad: "아쉬운점 없이 정말 잘 사용했습니다 ^^*",
    rating: 5,
    createdAt: "2022-09-02T20:45:48",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35211,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 12,
    subCategory_Name: "로션 & 에센스",
    barnd_Id: 655,
    barnd_Name: "스카이밀크",
    Product_Id: 82251790592,
    product_Title: "로션",
    user_Id: 5721,
    user_NickName: "angel1202",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/name30243331-12C6-4337-AFB8-D17624E19C3D.jpg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/name2FB0D7EF-5EAB-489D-9F4B-F26CA9E9BD0A.jpg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/nameF0F4BA8B-7AAC-4A10-AA3A-B8306C3A0466.jpg?",
    ProductReview_content:
      "21개월 아기인데 촉촉보다는 조금 건조해서 걱정이었는데, 스카이밀크 일주일 정도 발라주니 촉촉한 느낌이 들어요. 발림도 좋아서 바를 때 보들 보들 매끈 매끈해서 좋고~ 다른 것보다 흡수력도 좋아서 더 좋았어요! 도망치기가 엄청난 21개월 아기에게는 흡수력 좋은 로션이 짱이더라고요. 더불어 피부 건조한 저도 같이 사용해봤는데, 어른 피부에도 촉촉하니 좋았어요.",
    ProductReview_Content_bad:
      "향이 제 취향이 아니었어요. 뭔가 아가아가 느낌의 향을 원했는데 조금 아쉬웠어요-",
    rating: 5,
    createdAt: "2022-09-02T20:18:49",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35210,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 12,
    subCategory_Name: "로션 & 에센스",
    barnd_Id: 655,
    barnd_Name: "스카이밀크",
    Product_Id: 82251790592,
    product_Title: "로션",
    user_Id: 6793,
    user_NickName: "보라해요",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_6793_1662108250998.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_6793_1662108251062.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_6793_1662108251193.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_6793_1662108251320.jpeg?",
    ProductReview_content:
      "일단 사용하고 굉장히 만족했어요 아기가 5개월이 지나더니 갑자기 아토피가 생긴건지 너무 피부가 심하게 뒤짚어져서 약바르고 보습은 하루에 세 번 스카이밀크로션으로 해주고 있는데 많이 좋아졌구요. 지금은 사진보다 더 좋아졌어요. 성분이 무척 착하기도 하고 보습은 안 끈적하면서 흡수가 빨라서 목욕하고, 아침세수하고, 점심쯤 한번 더 발라줘요 그리고 개인적으로 엄마는 향기가 참 좋네요. 엄청 시원하고 부드러운 꽃향기가 나서 엄마 화장품으로도 자주 사용하구 있어요 ",
    ProductReview_Content_bad: "흡수력이 빨라 그런지 지속력이 조금 아쉬워요 ",
    rating: 5,
    createdAt: "2022-09-02T17:44:12",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35209,
    category_Id: 4,
    category_Name: "물티슈",
    subCategory_Id: 10,
    subCategory_Name: "물티슈",
    barnd_Id: 833,
    barnd_Name: "물따로",
    Product_Id: 82251780787,
    product_Title: "오리지날 캡형 물티슈",
    user_Id: 6730,
    user_NickName: "쏘으니",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_6730_1662340405706.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_6730_1662340406262.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_6730_1662340406591.jpeg?",
    ProductReview_content:
      "<체험단리뷰> 건티슈랑 물티슈 두가지 방법으로 사용할수있어서 편리해요 ㅎㅎ 사용하기 직전에 물을부어서 사용하기때문에 요즘 물티슈에관한 유해성분 이나 방부제 , 세균번식 에 대한 걱정이 많은데 물따로 물티슈는걱정없이 안심하고 사용할수있네요 ㅎㅎ 외출시 아이우유먹일때 가제수건 대용으로 건티슈 정말유용하게 잘사용했습니다 ㅎㅎ 밖에서 건티슈로 사용중에 물티슈가 필요할땐 보온병에있는물 살짝 부어 물티슈로 바로 사용할수있는점도 활용도가 굉장히 높습니다 .신생아용이라고 적힌만큼 부드러워서 신생아의 얼굴이나 엉덩이도 자극없이 닦이고 사용할수있어 좋아요 물티슈 한개에 적당한양이 들어있고 물티슈에 날짜를 적을수 있는 칸이 있어 기억하지 않아도 메모덕에 사용권장기한인 5일을 넘기지않고 사용할수있게 배려해주신부분도 센스있다 생각드네요 신생아있는집이라면 물따로물티슈 추천하고싶어요 ㅎㅎ",
    ProductReview_Content_bad: null,
    rating: 5,
    createdAt: "2022-09-02T15:25:55",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35208,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 12,
    subCategory_Name: "로션 & 에센스",
    barnd_Id: 655,
    barnd_Name: "스카이밀크",
    Product_Id: 82251790592,
    product_Title: "로션",
    user_Id: 3320,
    user_NickName: "💖오호마미",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_3320_1662100217937.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_3320_1662100218744.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_3320_1662100219697.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_3320_1662100220486.jpeg?",
    ProductReview_content:
      "[체험단 리뷰] 스카이 밀크로션 체험단에 당첨되었어요. 친환경🌱 종이포장으로 받았어요. 환경까지 생각하는 점 넘 좋으네요. 손등에 짜보니 촉촉한 크림이 원하는 양만큼 짜졌어요. 손가락으로 롤링하니 그냥 로션이 아니라 에센스 가득로션 처럼 촉촉했어요. 아이등에 도포해 문지르니 촉촉하게 약간 묽은크림이 쏘오옥 흡수가 되어서 좋으네요. 손으로 몸에 도포하는데 느낌이 너무나 부드러운거에요. 아이피부에 또 건조한 저의 피부에 두번 촉촉함을 주네요. 몸에 바르기 아까울 정도로 부드럽고 촉촉해요. 트러블이 있는 아이 피부에 쏵 스미니 첫찌도 탐을 내더라구요 동생 안볼때 얼굴에 도포하는 첫찌보고 좋은건 아이들이 먼저 아는 구나 했어요. 은은한 단꿈향 저는 나는건가 했어요. 은은해요. 좋은 크림 만나게 해준 🥰베럽체험단 감사합니다. ",
    ProductReview_Content_bad:
      "저는 너무나 만족하며 썻구요. 흡수가 빨라서 건조한 가을 겨울에는 오일이나 크림 한번더 도포해야 할것 같아요.",
    rating: 5,
    createdAt: "2022-09-02T15:21:03",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35207,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 12,
    subCategory_Name: "로션 & 에센스",
    barnd_Id: 655,
    barnd_Name: "스카이밀크",
    Product_Id: 82251790592,
    product_Title: "로션",
    user_Id: 3277,
    user_NickName: "아기곰",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_3277_1662097247911.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_3277_1662097248394.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_3277_1662097248714.jpeg?",
    ProductReview_content:
      "체험단 후기 ㄹ완전 고보습 촉촉해요~ 아기 우둘투둘 피부도 많이 좋아졌어요 저도 피부가 건조한편이라 같이 잘 쓰고 있어요 ^^ ",
    ProductReview_Content_bad:
      "가격이 조금 사악하긴하나 제품성분이나 효과는 아쉬운점 없이 잘 사용 하고 있어요 ^^ ",
    rating: 5,
    createdAt: "2022-09-02T14:40:11",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35206,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 12,
    subCategory_Name: "로션 & 에센스",
    barnd_Id: 655,
    barnd_Name: "스카이밀크",
    Product_Id: 82251790592,
    product_Title: "로션",
    user_Id: 12893,
    user_NickName: "하남매마미",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_12893_1662043449998.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_12893_1662043450060.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_12893_1662043450114.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_12893_1662043450170.jpeg?",
    ProductReview_content:
      "[체험단 리뷰] 데일리로 쓰기 좋은 로션이에요!! 마스크만 조금 오래 써도 붉어지는 피부인데, 그게 바르자마자 진정되더라구요~ 첨들어본 당나귀밀크를 사용한 로션이었는데 기볍게 발려서 데일리로 자주발라주기 너무 좋아요~",
    ProductReview_Content_bad:
      "용량에 비해 가성비가 좋지는 않은것같아요ㅠㅠㅠ 한번 누르면 푹 하고 많이씩 나와버려서, 펌프형식이었으면 더 더 만족했을것같아요!",
    rating: 5,
    createdAt: "2022-09-01T23:44:11",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35205,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 12,
    subCategory_Name: "로션 & 에센스",
    barnd_Id: 655,
    barnd_Name: "스카이밀크",
    Product_Id: 82251790592,
    product_Title: "로션",
    user_Id: 6130,
    user_NickName: "짱짱쑤",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/name4D05628D-96A0-4897-8D65-16EA199AFB87.jpg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/nameB664E2FD-CF72-4047-BAFD-EDAC2AF63154.jpg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/nameC5B035FF-1C94-440D-987E-73890C2FAD68.jpg?",
    ProductReview_content:
      "당나귀밀크로 만든 순하고 보습력 좋은 로션 체험단이 되어 사용해보았어요 당나귀밀크는 처음 들어봤는데 상처회복 촉진 등에 쓰이는 EGF성분이 일반우유, 산양유 등보다 약 4배나 풍부하다고 해요 매일 덕지덕지 바르는 덕에 건조할 틈 없고! 보습력이 오래 가지는 않았지만 촉촉! 피부 진정은 물론이고 피부장벽 개선까지 해준데요 살짝 묽은감이 있는 흰색 제형인데, 끈적함은 없었고 몽글몽글한 텍스처가 맘에 들었어요 그리고 개인적으로 맘에들었던건 향이였어요 스카이밀크로션 향은 자사가 개발한 단꿈향! 포근하고 행복한 꿈나라의 향을 전달한다고 해요",
    ProductReview_Content_bad:
      "가격부분에서 아쉬웠다 그리고 향은 호불호가 있을것 같다 무향으로 된 제품도 나오면 좋을것같다",
    rating: 4,
    createdAt: "2022-09-01T23:40:25",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35204,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 12,
    subCategory_Name: "로션 & 에센스",
    barnd_Id: 211,
    barnd_Name: "일리윤",
    Product_Id: 82251780740,
    product_Title: "세라마이드 아토 로션",
    user_Id: 14508,
    user_NickName: "은총총",
    ProductReview_Url: null,
    ProductReview_content:
      "육아선배인 친구에게 추천받아서 사용하기시작했어요. 성분이 워낙 괜찮고 무향이라 만족스럽게 사용중이예요. 트레이더스에서 할인할때 쟁여두고 쓰고있어요!",
    ProductReview_Content_bad:
      "흡수력이 조금 아쉬워요ㅠ 그래도 이만한 가성비템이 없는것같아 계속 사용중입니당",
    rating: 4,
    createdAt: "2022-09-01T22:14:34",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35203,
    category_Id: 1,
    category_Name: "간식",
    subCategory_Id: 4,
    subCategory_Name: "음료",
    barnd_Id: 2035,
    barnd_Name: "맘스초이스",
    Product_Id: 82251788034,
    product_Title: "배도라지주스",
    user_Id: 9319,
    user_NickName: "친절한금자씨",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_9319_1662030067655.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_9319_1662030067882.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_9319_1662030068094.jpeg?",
    ProductReview_content:
      "맘스초이스 배도라지 배와 도라지 단 두가지로 만들었어요 다른 첨가물이 없어서 걱정없이 먹을 수 있다는 점이 최대 장점입니다 박스부터 아기것처럼 아기자기 예뿌구요 ㅎㅎ 7개가 들어있어요 일주일분으로 식탁에 꺼내두고 먹기가 편합니다 한팩에는 넉넉히 120ml 씩 들어 있어요 컵에 따라마셔도 되고 팩 채로 빨아먹을수도 있게 편하게 되어 있습니다 첨엔 설탕들어갔나싶게 달달하고 맛있어서 의심했어요 근데 아무리 눈씻고 찾아봐도 첨가물은 없네요 전 진짜 맛있더라구요 쓴 맛도 없구요 아기는 물론 첨엔 거부반응 의심을 무지하면서 먹는데 한입보고는 잘 받아먹어요 첨엔 숟가락으로 떠서 맛보게 하고 나중엔 컵에 따라서 줍니다 지금 환절기에 코로나 독감도 유행이라고 하는데 배도라지즙 하나로 예방하는 느낌이예요 아플때도 필요하지만 미리 튼튼하게 준비해두면 더 좋겠죠 아주아주 만족합니다 베럽체험단으로 선정되어 체험 후 남기는 후기입니다",
    ProductReview_Content_bad:
      "아쉬운점은 특별히 찾지는 못했어요 유해한 첨가물 없이 맛도 있어서 좋았답니다",
    rating: 5,
    createdAt: "2022-09-01T19:57:51",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35202,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 13,
    subCategory_Name: "오일",
    barnd_Id: 869,
    barnd_Name: "아델",
    Product_Id: 82251782574,
    product_Title: "맘& 베이베 유기농 오일",
    user_Id: 14455,
    user_NickName: "귤찡맘",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/name6BEC796B-4593-4FBE-A305-6E80785ADE83.jpg?",
    ProductReview_content:
      "아기와 엄마가 모두 쓸수있는 오일💛 다른 오일에 비해 값이 나가지만 제품 퀄리티 무시못하죠💛",
    ProductReview_Content_bad: null,
    rating: 5,
    createdAt: "2022-09-01T19:09:08",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35201,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 12,
    subCategory_Name: "로션 & 에센스",
    barnd_Id: 655,
    barnd_Name: "스카이밀크",
    Product_Id: 82251790592,
    product_Title: "로션",
    user_Id: 8164,
    user_NickName: "자연주의",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_8164_1662195018343.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_8164_1662195019245.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_8164_1662195019818.jpeg?",
    ProductReview_content:
      "♥체험단 리뷰♥ - 수분감이 많은 로션제형으로 바르면 바로 수분 보호막이 형성되어 굉장히 시원하고 촉촉해요. 한팔에는 베베루미 크림, 다른팔에는 스카이밀크로션을 같은 양 짜서 발랐는데.. 스카이밀크를 바른 쪽이 더 촉촉해 시원했어요. - 발림성도 좋고 백탁도 적습니다. 하지만 바르면서 좀 많이 두드려 주지 않으면 좀 끈적여요. 아이 몸에 발라주고 나면 손 마디 등이 좀 끈적입니다. -봄 여름 가을에는 촉촉하고 산뜻한 스카이밀크로션, 겨울에는 보습이 더 잘되는 스카이밀크 크림이 좋을 것같아요. ",
    ProductReview_Content_bad:
      " -전성분 그린등급인데 향료만 제외라서 아쉽습니다. 향료는 향료로만 표기되어 무슨 성분인지 알기가 어려워서 알레르기를 일으키는 성분이 있는지 확인을 할수없어 안타깝습니다. 향료만 없으면 수분감 촉촉함 모든 면에서 완벽하네요~ -용기가 너무 얇아 한번 쓰고 외부 표면이 우글우글 찌그러지네요. -2백미리 배송비포함 2만원 정도로 아토팜로션200미리 배송비 포함 만오천원 정도이고 할인행사도 많이하니 스카이밀크가 조금 비싼 감은 있는 것 같습니다.",
    rating: 4,
    createdAt: "2022-09-01T16:32:13",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35200,
    category_Id: 4,
    category_Name: "물티슈",
    subCategory_Id: 10,
    subCategory_Name: "물티슈",
    barnd_Id: 333,
    barnd_Name: "마미요",
    Product_Id: 82251779080,
    product_Title: "시그니처 아기물티슈 캡형",
    user_Id: 13477,
    user_NickName: "도도수진",
    ProductReview_Url: null,
    ProductReview_content:
      "일단 두깨가 너무 두껍지도 얇지도 않은 부담없이 쓸수있는 평형 ! 거기에 따른 저렴한가격이라 다쓰고 재구매예정 여러브랜드제품을 다써봐도 이렇게 딱딱 1장씩 뽑히는애는 처음ㅋ 애기도한장씩 뽑히니 잘뽑아서 스스로닦아요ㅎㅎ 적당한수분감이 있어좋아요. 어떤건 넘축축해서ㅠ불편한데 일상생활에서도, 아이한테도 딱 쓰기좋은 물티슈. 별5개 쾅쾅",
    ProductReview_Content_bad:
      "아쉬운점은딱히없음 딜많이해서 저렴하게더살수잇음좋겠어요",
    rating: 5,
    createdAt: "2022-09-01T14:33:41",
    status: "ACTIVATE",
    addYN: "N",
    deductYN: "N",
  },
  {
    review_Id: 35199,
    category_Id: 8,
    category_Name: "생활용품",
    subCategory_Id: 33,
    subCategory_Name: "젖꼭지",
    barnd_Id: 75,
    barnd_Name: "더블하트",
    Product_Id: 82251784015,
    product_Title: "소프트터치 모유실감 젖꼭지 SS",
    user_Id: 342,
    user_NickName: "쥐순이마밍",
    ProductReview_Url: null,
    ProductReview_content:
      "조리원 퇴소하고 집에 와서부터 31일차인 아이가 쓰고 있는데 세척도 간편하고 쉽게 찢어지지 않아서 좋더라구요 아직까지는 끙끙거리지 않아서 50일까지는 ss젖꼭지 쓸듯 합니다 더블하트 젖병 외에도 호환되는게 은근 많아서 좋은거 같아요",
    ProductReview_Content_bad:
      "아무래도 가격이 조금 비싸다는 점? 오래 못쓰는거에 비해 부담스러워요",
    rating: 5,
    createdAt: "2022-09-01T13:02:28",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35198,
    category_Id: 2,
    category_Name: "분유",
    subCategory_Id: 6,
    subCategory_Name: "국내분유",
    barnd_Id: 54,
    barnd_Name: "앱솔루트",
    Product_Id: 82251787127,
    product_Title: "리뉴얼 앱솔루트 명작 2FL 분유 1단계",
    user_Id: 342,
    user_NickName: "쥐순이마밍",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/name8A4E1482-5834-4C79-9144-B2A00DD7FC75.jpg?",
    ProductReview_content:
      "둘째가 현재 먹고 있는 분유에요 조리원에서 퇴소하고 명작으로 갈아탔는데 배앓이도 없었고 무엇보다 하루 한 번 꼭 응아하더라구요! 가루 입자도 곱고 분유 탈때에 잘 녹아서 거품도 덜 생기는거 같아요 가격도 부담스럽지 않아서 진짜 강추해요!",
    ProductReview_Content_bad: "아쉬운 점 없는 만족스러운 분유에요",
    rating: 5,
    createdAt: "2022-09-01T12:59:49",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35197,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 12,
    subCategory_Name: "로션 & 에센스",
    barnd_Id: 81,
    barnd_Name: "몽디에스",
    Product_Id: 82251778590,
    product_Title: "엑설런트 아토 로션",
    user_Id: 14455,
    user_NickName: "귤찡맘",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/name8ED9BE8A-2267-450F-8B14-2AEF2824989C.jpg?",
    ProductReview_content:
      "몽디에스는 바스앤샴푸도 좋고 라인이 다 맘에 들어요. 향도 은은하고 아기 피부 보습 책임져주네요💛",
    ProductReview_Content_bad: null,
    rating: 5,
    createdAt: "2022-09-01T01:28:41",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35196,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 12,
    subCategory_Name: "로션 & 에센스",
    barnd_Id: 134,
    barnd_Name: "아토오겔",
    Product_Id: 82251778254,
    product_Title: "베이비 로션",
    user_Id: 14455,
    user_NickName: "귤찡맘",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/nameA1CE6D1C-D0F0-4EBF-96CD-13541BA7E327.jpg?",
    ProductReview_content:
      "쏘쏘... 크게 좋지도 크게 나쁘지도 않아여 아기가 쓰다가 피부가 좋아지를걸 느끼지못해서 신랑이 사용중...",
    ProductReview_Content_bad: "없음",
    rating: 3,
    createdAt: "2022-09-01T01:26:31",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35195,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 11,
    subCategory_Name: "바디워시",
    barnd_Id: 81,
    barnd_Name: "몽디에스",
    Product_Id: 82251778026,
    product_Title: "바스 앤드 샴푸",
    user_Id: 14455,
    user_NickName: "귤찡맘",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/nameFE7857D0-95F8-4B8D-AE46-DBCBDEFAFCD7.jpg?",
    ProductReview_content:
      "향 맘에 들어요. 몽디에스 말해 모해요. 로션이랑 다같이 쓰고있는데 보습 넘 좋아여 촉촉하고",
    ProductReview_Content_bad: "없음",
    rating: 5,
    createdAt: "2022-09-01T01:17:19",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35194,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 11,
    subCategory_Name: "바디워시",
    barnd_Id: 78,
    barnd_Name: "닥터바이오",
    Product_Id: 82251778595,
    product_Title: "에코 올인원 클렌저",
    user_Id: 14455,
    user_NickName: "귤찡맘",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/name336D04CA-F4B3-4E98-829F-B0EC25E0E333.jpg?",
    ProductReview_content:
      "인청받은 성분이라 걱정없이 아가랑 잘썼습니다. 머리부터 발끝까지 하나로 끝낼수있어 넘 좋구 온가족 사용할수 있어 편리합니다.",
    ProductReview_Content_bad:
      "제형이 쬐끔 묽은감이 있긴한데 크게 문제가 되진않아요. 거품형으로도 쓸수있게 나오면 졸을것같아요!",
    rating: 5,
    createdAt: "2022-09-01T01:13:36",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
  {
    review_Id: 35193,
    category_Id: 5,
    category_Name: "스킨바디케어",
    subCategory_Id: 12,
    subCategory_Name: "로션 & 에센스",
    barnd_Id: 655,
    barnd_Name: "스카이밀크",
    Product_Id: 82251790592,
    product_Title: "로션",
    user_Id: 5438,
    user_NickName: "여신차차",
    ProductReview_Url:
      "https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_5438_1661959355674.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_5438_1661959355849.jpeg?,https://beluv-images.s3.ap-northeast-2.amazonaws.com/review_images/review_5438_1661959355941.jpeg?",
    ProductReview_content:
      "💗체험리뷰💗 아기가 아토피초기피부에서 벗어나지 못하고 18개월인 지금까지 아토피초기피부에 심한 건성 피부에요😢.. 보습이 약한 로션,크림은 쳐다도 안보게되는데 스카이밀크 로션은 보습력도 꽤 좋은편이고 발림성도 촉촉하게 백탁현상 없이 잘 발려져서 손이 자연스레 가게되는 제품이에요🤗 🌈 EWG 그린등급 🌈 피부자극 저자극 판정 🌈 피부장벽 개선도움 🌈 알러젠 성분 불검출 판정 당나귀 밀크와 4가지 식물유래 성분이 건강한 피부 환경 유지에 도움을 줘서 미백,항염,항산화에 도움을 준다고 하네요😊 향도 인공적인 향이 아니라 아기한테 바르고나서 킁킁 좋은 냄새를 맡게 되서 참 좋아요😍 ",
    ProductReview_Content_bad:
      "용량대비 가격이 높아 살짝 아쉬워요ㅠ.ㅠ 보습이 중요한 아기다보니 한통은 금방써버리는데 막쓰기엔 가격이 부담스럽긴 하네요😂ㅎㅎ ",
    rating: 5,
    createdAt: "2022-09-01T00:22:39",
    status: "ACTIVATE",
    addYN: "Y",
    deductYN: "N",
  },
];
